export const HEALTH_FACTOR = {
    TARGET_BALANCED: 1.25,
    CRITICAL_BALANCED: 1.21,
    TARGET_CONSERVATIVE: 1.40,
    CRITICAL_CONSERVATIVE: 1.35,
    TARGET_AGGRESSIVE: 1.15,
    CRITICAL_AGGRESSIVE: 1.11,
};

export const ALLOCATION = {
    PENDLE: 0.55,
    RWA: 0.20,
    ETHENA: 0.15,
    BOROS: 0.05,
    MORPHO: 0.05,
};
